version: "3.9"

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emplois
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./BDD_docker.sql:/docker-entrypoint-initdb.d/BDD_docker.sql

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass

volumes:
  db_data: